name: mpocket
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  audio_metadata_extractor: ^0.0.4
  audioplayers: ^6.1.0
  build_runner: ^2.4.12
  ffi: ^2.1.3
  flutter:
    sdk: flutter
  form_controller: ^0.8.8+2
  gap: ^3.0.1
  go_router: ^14.2.6
  json_annotation: ^4.9.0
  json_model: ^1.0.0
  just_audio: ^0.9.42
  list_picker: ^1.2.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  wifi_scan: ^0.4.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/translation/
    - assets/image/