// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

import 'package:ffi/ffi.dart';

/// Bindings for `src/libmoc.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class LibmocBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  LibmocBindings(ffi.DynamicLibrary dynamicLibrary)
  : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  LibmocBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
    lookup)
  : _lookup = lookup;

  /// A very short-lived native function.
  ///
  /// For very short-lived functions, it is fine to call them on the main isolate.
  /// They will block the Dart execution while running the native function, so
  /// only do this for native functions which are guaranteed to be short-lived.
  int sum(
    int a,
    int b,
  ) {
    return _sum(
      a,
      b,
    );
  }

  late final _sumPtr =
  _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Int)>>('sum');
  late final _sum = _sumPtr.asFunction<int Function(int, int)>();

  /// A longer lived native function, which occupies the thread calling it.
  ///
  /// Do not call these kind of native functions in the main isolate. They will
  /// block Dart execution. This will cause dropped frames in Flutter applications.
  /// Instead, call these native functions on a separate isolate.
  int sum_long_running(
    int a,
    int b,
  ) {
    return _sum_long_running(
      a,
      b,
    );
  }
  late final _sum_long_runningPtr =
  _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Int)>>(
    'sum_long_running');
  late final _sum_long_running =
  _sum_long_runningPtr.asFunction<int Function(int, int)>();


  // discovery
  ffi.Pointer<ffi.Int8> mnet_discovery(
  ) {
    return _mnet_discovery (
    );
  }
  late final _mnet_discoveryPtr =
  _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Int8> Function()>>(
    'mnetDiscovery');
  late final _mnet_discovery =
  _mnet_discoveryPtr.asFunction<ffi.Pointer<ffi.Int8> Function()>();

  // discover2
  ffi.Pointer<ffi.Int8> mnet_discover2(
  ) {
    return _mnet_discover2 (
    );
  }
  late final _mnet_discover2Ptr =
  _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Int8> Function()>>(
    'mnet_discover2');
  late final _mnet_discover2 =
  _mnet_discover2Ptr.asFunction<ffi.Pointer<ffi.Int8> Function()>();

  // file_test
  ffi.Pointer<ffi.Int8> mfile_test(
    ffi.Pointer<ffi.Int8> dirname
  ) {
    return _mfile_test (
      dirname
    );
  }
  late final _mfile_testPtr =
  _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Int8> Function(ffi.Pointer<ffi.Int8>)>>(
    'mfile_test');
  late final _mfile_test =
  _mfile_testPtr.asFunction<ffi.Pointer<ffi.Int8> Function(ffi.Pointer<ffi.Int8>)>();

  int mnetStart() {return _mnetStart();}
  late final _mnetStartPtr = _lookup<ffi.NativeFunction<ffi.Int Function()>>('mnetStart');
  late final _mnetStart = _mnetStartPtr.asFunction<int Function()>();

  int wifiSet(ffi.Pointer<Utf8>ID, ffi.Pointer<Utf8> ap, ffi.Pointer<Utf8>pass, ffi.Pointer<Utf8>name, ffi.Pointer<Utf8>callback) {return _wifiSet(ID, ap, pass, name, callback);}
  late final _wifiSetPtr = _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<Utf8>, ffi.Pointer<Utf8>, ffi.Pointer<Utf8>, ffi.Pointer<Utf8>, ffi.Pointer<Utf8>)>>('mnetWifiSet');
  late final _wifiSet = _wifiSetPtr.asFunction<int Function(ffi.Pointer<Utf8>, ffi.Pointer<Utf8>, ffi.Pointer<Utf8>, ffi.Pointer<Utf8>, ffi.Pointer<Utf8>)>();

}
